ignore_merge_commits = true

[changelog]
path = "CHANGELOG.md"

[packages.agent-core]
path = "packages/agent-core"
public_api = true
changelog_path = "packages/agent-core/CHANGELOG.md"
pre_bump_hooks = [
    "echo 'bumping agent-core from {{latest|0.0.0}} to {{version|0.0.1}}'",
    "pnpm pkg set version={{version|0.0.1}}",
]

post_bump_hooks = [
    "git push",
    "git push origin --tags",
]

[packages.agent-runtime]
path = "packages/agent-runtime"
public_api = false
changelog_path = "packages/agent-runtime/CHANGELOG.md"
pre_bump_hooks = [
    "echo 'bumping agent-runtime from {{latest|0.0.0}} to {{version|0.0.1}}'",
    "pnpm pkg set version={{version|0.0.1}}",
]

post_bump_hooks = [
    "git push",
    "git push origin --tags",
]
